import React from "react";

import gazet from "@/images/gazet.png";
import hands from "@/images/hands.png";
import message from "@/images/message.png";
import Image from "next/image";
import { BsArrowDown } from "react-icons/bs";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by Merkez",
};

const page = () => {
  return (
    <React.Fragment>
      <div className="w-full max-w-[1920px] bg-[#0D0D0D] py-[96px] ">
        <div className="w-340 mx-auto flex items-start justify-between">
          <div className="w-1/2  ">
            <div className="flex mb-4 items-center justify-start gap-2 ">
              <div className="h-px w-5 bg-[#C8401A] rounded-md "></div>
              <h1 className="font-sans font-normal text-[13px] text-[#C8401A] uppercase tracking-[1.5px] ">
                Contact Folio
              </h1>
            </div>
            <h1 className="text-[57px] w-[70%] text-[#FAF9F6] font-[play400] mb-4 leading-16 ">
              Let's start a{" "}
              <span className="font-[playitalic] italic text-amber-300 ">
                conversation.
              </span>
            </h1>

            <p className="text-[#FAF9F68C] font-sans font-normal text-[17px] ">
              Whether you're a reader with a suggestion, a publisher wanting to
              contribute, or an institution interested in partnership — we read
              every message.
            </p>
          </div>

          <div className="w-1/2 flex flex-col items-baseline justify-center gap-3 ">
            <div className="w-full bg-[#FFFFFF0A] border border-[#FFFFFF14] rounded-md py-4 px-6 flex items-center justify-start gap-4 ">
              <Image width={44} height={44} src={hands} alt="hands" />

              <div className="flex flex-col items-baseline justify-start gap-1 ">
                <p className="text-[17px] font-sans font-normal text-[#FAF9F659] ">
                  General enquiries
                </p>

                <p className="text-[17px] font-sans font-normal text-[#FAF9F6]  ">
                  hello@folio.org
                </p>
              </div>
            </div>

            <div className="w-full bg-[#FFFFFF0A] border border-[#FFFFFF14] rounded-md py-4 px-6 flex items-center justify-start gap-4 ">
              <Image width={44} height={44} src={gazet} alt="hands" />

              <div className="flex flex-col items-baseline justify-start gap-1 ">
                <p className="text-[17px] font-sans font-normal text-[#FAF9F659] ">
                  General enquiries
                </p>

                <p className="text-[17px] font-sans font-normal text-[#FAF9F6]  ">
                  hello@folio.org
                </p>
              </div>
            </div>

            <div className="w-full bg-[#FFFFFF0A] border border-[#FFFFFF14] rounded-md py-4 px-6 flex items-center justify-start gap-4 ">
              <Image width={44} height={44} src={message} alt="hands" />

              <div className="flex flex-col items-baseline justify-start gap-1 ">
                <p className="text-[17px] font-sans font-normal text-[#FAF9F659] ">
                  General enquiries
                </p>

                <p className="text-[17px] font-sans font-normal text-[#FAF9F6]  ">
                  hello@folio.org
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full max-w-[1920px] py-[84px] ">
        <div className="w-340 mx-auto ">
          <div className="w-full flex items-start gap-8 justify-between mb-16 ">
            <div className="w-1/2  ">
              <div className="py-6 px-4 rounded-2xl bg-[#0D0D0D] mb-[76px] ">
                <p className="uppercase text-[#FAF9F659] font-sans font-normal text-[11px] mb-3 ">
                  Average response time
                </p>

                <p className=" text-[#FAF9F6] font-[sans] font-normal text-[44px] mb-2 ">
                  18h
                </p>
                <p className="text-[#FAF9F666] font-sans font-normal text-[13px] mb-4 ">
                  Business hours
                </p>

                <div className="w-full bg-[#FFFFFF1A] rounded-md h-1 mb-3 ">
                  <div className="h-full w-[70%] bg-[#C8401A] rounded-md "></div>
                </div>

                <p className="text-[#FAF9F666] w-[70%] font-sans font-normal text-[13px]">
                  72% of enquiries answered within one business day. We aim to
                  respond to every message personally — no bot replies.
                </p>
              </div>

              <div className="w-full border border-[#DDD9D0] bg-[#FAF9F6] py-6 px-6 rounded-2xl ">
                <h1>Get in touch directly</h1>

                <div className="w-full divide-y divide-[#DDD9D0] ">
                  <div className="w-full flex items-center py-3 justify-start gap-3 ">
                    <div>
                      <Image
                        src={message}
                        alt="message"
                        width={32}
                        height={32}
                      />
                    </div>

                    <div className="flex flex-col items-baseline justify-start gap-1 ">
                      <p className="uppercase text-[#A8A69F] font-sans font-normal text-[12px] ">
                        General
                      </p>
                      <p className=" text-[#0D0D0D] font-sans font-normal text-[14px]  ">
                        hello@folio.org
                      </p>
                      <p className="text-[#7A7870] font-sans font-normal text-[14px]  ">
                        Readers, suggestions, feedback
                      </p>
                    </div>
                  </div>

                  <div className="w-full flex items-center py-3 justify-start gap-3 ">
                    <div>
                      <Image src={hands} alt="message" width={32} height={32} />
                    </div>

                    <div className="flex flex-col items-baseline justify-start gap-1 ">
                      <p className="uppercase text-[#A8A69F] font-sans font-normal text-[12px] ">
                        General
                      </p>
                      <p className=" text-[#0D0D0D] font-sans font-normal text-[14px]  ">
                        hello@folio.org
                      </p>
                      <p className="text-[#7A7870] font-sans font-normal text-[14px]  ">
                        Readers, suggestions, feedback
                      </p>
                    </div>
                  </div>

                  <div className="w-full flex items-center py-3 justify-start gap-3 ">
                    <div>
                      <Image src={gazet} alt="message" width={32} height={32} />
                    </div>

                    <div className="flex flex-col items-baseline justify-start gap-1 ">
                      <p className="uppercase text-[#A8A69F] font-sans font-normal text-[12px] ">
                        General
                      </p>
                      <p className=" text-[#0D0D0D] font-sans font-normal text-[14px]  ">
                        hello@folio.org
                      </p>
                      <p className="text-[#7A7870] font-sans font-normal text-[14px]  ">
                        Readers, suggestions, feedback
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="w-1/2 border border-[#DDD9D0] bg-[#FAF9F6] py-6 px-6 rounded-2xl h-full "></div>
          </div>

          {/* FAQ */}
          <div className="w-full border border-[#DDD9D0] bg-[#FAF9F6] py-4 divide-y divide-[#DDD9D0] rounded-2xl ">
            <h1 className="text-[#A8A69F] px-5 py-2 uppercase font-sans font-normal text-[11px] tracking-[1px] ">
              Frequently Asked
            </h1>

            <div className="w-full flex items-center justify-between px-5 py-4 ">
              <p className="text-[#0D0D0D] font-sans font-normal text-[13px] ">
                How do I submit a magazine to FOLIO?
              </p>
              <BsArrowDown className="text-[#A8A69F] text-[12px] " />
            </div>

            <div className="w-full flex items-center justify-between px-5 py-4 ">
              <p className="text-[#0D0D0D] font-sans font-normal text-[13px] ">
                How do I submit a magazine to FOLIO?
              </p>
              <BsArrowDown className="text-[#A8A69F] text-[12px] " />
            </div>
            <div className="w-full flex items-center justify-between px-5 py-4 ">
              <p className="text-[#0D0D0D] font-sans font-normal text-[13px] ">
                How do I submit a magazine to FOLIO?
              </p>
              <BsArrowDown className="text-[#A8A69F] text-[12px] " />
            </div>
            <div className="w-full flex items-center justify-between px-5 pt-4 ">
              <p className="text-[#0D0D0D] font-sans font-normal text-[13px] ">
                How do I submit a magazine to FOLIO?
              </p>
              <BsArrowDown className="text-[#A8A69F] text-[12px] " />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
};

export default page;
