import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "About",
  description: "Generated by Merkez",
};

const page = () => {
  return (
    <div>
      
    </div>
  )
}

export default page
