// import { Metadata } from 'next';
import React from 'react'

// export const metadata: Metadata = {
//   title: "Issues",
//   description: "Generated by Merkez",
// };

const IssuesPage = () => {
  return (
    <div>
      All Issues
    </div>
  )
}

export default IssuesPage
